// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: builders.sql

package db

import (
	"context"
)

const getHealthyBuilders = `-- name: GetHealthyBuilders :many
SELECT id, name, address, arch, status, last_seen_at, created_at FROM builders WHERE status = 'healthy'
  AND last_seen_at > NOW() - INTERVAL '30 seconds'
ORDER BY last_seen_at DESC
`

func (q *Queries) GetHealthyBuilders(ctx context.Context) ([]Builder, error) {
	rows, err := q.db.QueryContext(ctx, getHealthyBuilders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Builder
	for rows.Next() {
		var i Builder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Arch,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuilders = `-- name: ListBuilders :many
SELECT id, name, address, arch, status, last_seen_at, created_at FROM builders ORDER BY last_seen_at DESC
`

func (q *Queries) ListBuilders(ctx context.Context) ([]Builder, error) {
	rows, err := q.db.QueryContext(ctx, listBuilders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Builder
	for rows.Next() {
		var i Builder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Arch,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBuilderHeartbeat = `-- name: UpdateBuilderHeartbeat :exec
UPDATE builders SET last_seen_at = NOW(), status = $2 WHERE name = $1
`

type UpdateBuilderHeartbeatParams struct {
	Name   string `json:"name"`
	Status string `json:"status"`
}

func (q *Queries) UpdateBuilderHeartbeat(ctx context.Context, arg UpdateBuilderHeartbeatParams) error {
	_, err := q.db.ExecContext(ctx, updateBuilderHeartbeat, arg.Name, arg.Status)
	return err
}

const upsertBuilder = `-- name: UpsertBuilder :one
INSERT INTO builders (name, address, arch)
VALUES ($1, $2, $3)
ON CONFLICT (name) DO UPDATE
  SET address = EXCLUDED.address, arch = EXCLUDED.arch, last_seen_at = NOW(), status = 'healthy'
RETURNING id, name, address, arch, status, last_seen_at, created_at
`

type UpsertBuilderParams struct {
	Name    string `json:"name"`
	Address string `json:"address"`
	Arch    string `json:"arch"`
}

func (q *Queries) UpsertBuilder(ctx context.Context, arg UpsertBuilderParams) (Builder, error) {
	row := q.db.QueryRowContext(ctx, upsertBuilder, arg.Name, arg.Address, arg.Arch)
	var i Builder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Arch,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}
