// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: builds.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createBuild = `-- name: CreateBuild :one
INSERT INTO builds (project_id, builder_id, status) VALUES ($1, $2, 'pending') RETURNING id, project_id, builder_id, status, image_ref, cache_hit, started_at, finished_at, created_at
`

type CreateBuildParams struct {
	ProjectID uuid.UUID     `json:"project_id"`
	BuilderID uuid.NullUUID `json:"builder_id"`
}

func (q *Queries) CreateBuild(ctx context.Context, arg CreateBuildParams) (Build, error) {
	row := q.db.QueryRowContext(ctx, createBuild, arg.ProjectID, arg.BuilderID)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BuilderID,
		&i.Status,
		&i.ImageRef,
		&i.CacheHit,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getBuild = `-- name: GetBuild :one
SELECT id, project_id, builder_id, status, image_ref, cache_hit, started_at, finished_at, created_at FROM builds WHERE id = $1
`

func (q *Queries) GetBuild(ctx context.Context, id uuid.UUID) (Build, error) {
	row := q.db.QueryRowContext(ctx, getBuild, id)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BuilderID,
		&i.Status,
		&i.ImageRef,
		&i.CacheHit,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getBuildLogs = `-- name: GetBuildLogs :many
SELECT id, build_id, ts, line FROM build_logs WHERE build_id = $1 ORDER BY id ASC
`

func (q *Queries) GetBuildLogs(ctx context.Context, buildID uuid.UUID) ([]BuildLog, error) {
	rows, err := q.db.QueryContext(ctx, getBuildLogs, buildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuildLog
	for rows.Next() {
		var i BuildLog
		if err := rows.Scan(
			&i.ID,
			&i.BuildID,
			&i.Ts,
			&i.Line,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBuildLog = `-- name: InsertBuildLog :exec
INSERT INTO build_logs (build_id, line) VALUES ($1, $2)
`

type InsertBuildLogParams struct {
	BuildID uuid.UUID `json:"build_id"`
	Line    string    `json:"line"`
}

func (q *Queries) InsertBuildLog(ctx context.Context, arg InsertBuildLogParams) error {
	_, err := q.db.ExecContext(ctx, insertBuildLog, arg.BuildID, arg.Line)
	return err
}

const listBuildsByProject = `-- name: ListBuildsByProject :many
SELECT id, project_id, builder_id, status, image_ref, cache_hit, started_at, finished_at, created_at FROM builds WHERE project_id = $1 ORDER BY created_at DESC LIMIT 50
`

func (q *Queries) ListBuildsByProject(ctx context.Context, projectID uuid.UUID) ([]Build, error) {
	rows, err := q.db.QueryContext(ctx, listBuildsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Build
	for rows.Next() {
		var i Build
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.BuilderID,
			&i.Status,
			&i.ImageRef,
			&i.CacheHit,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startBuild = `-- name: StartBuild :exec
UPDATE builds SET status = 'running', started_at = NOW() WHERE id = $1
`

func (q *Queries) StartBuild(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, startBuild, id)
	return err
}

const updateBuildStatus = `-- name: UpdateBuildStatus :exec
UPDATE builds SET status = $2, finished_at = $3, cache_hit = $4, image_ref = $5 WHERE id = $1
`

type UpdateBuildStatusParams struct {
	ID         uuid.UUID      `json:"id"`
	Status     string         `json:"status"`
	FinishedAt sql.NullTime   `json:"finished_at"`
	CacheHit   bool           `json:"cache_hit"`
	ImageRef   sql.NullString `json:"image_ref"`
}

func (q *Queries) UpdateBuildStatus(ctx context.Context, arg UpdateBuildStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateBuildStatus,
		arg.ID,
		arg.Status,
		arg.FinishedAt,
		arg.CacheHit,
		arg.ImageRef,
	)
	return err
}
