// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ApiToken struct {
	ID         uuid.UUID    `json:"id"`
	ProjectID  uuid.UUID    `json:"project_id"`
	TokenHash  string       `json:"token_hash"`
	Label      string       `json:"label"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	CreatedAt  time.Time    `json:"created_at"`
}

type Build struct {
	ID         uuid.UUID      `json:"id"`
	ProjectID  uuid.UUID      `json:"project_id"`
	BuilderID  uuid.NullUUID  `json:"builder_id"`
	Status     string         `json:"status"`
	ImageRef   sql.NullString `json:"image_ref"`
	CacheHit   bool           `json:"cache_hit"`
	StartedAt  sql.NullTime   `json:"started_at"`
	FinishedAt sql.NullTime   `json:"finished_at"`
	CreatedAt  time.Time      `json:"created_at"`
}

type BuildLog struct {
	ID      int64     `json:"id"`
	BuildID uuid.UUID `json:"build_id"`
	Ts      time.Time `json:"ts"`
	Line    string    `json:"line"`
}

type Builder struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	Address    string    `json:"address"`
	Arch       string    `json:"arch"`
	Status     string    `json:"status"`
	LastSeenAt time.Time `json:"last_seen_at"`
	CreatedAt  time.Time `json:"created_at"`
}

type Project struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
}
