// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createToken = `-- name: CreateToken :one
INSERT INTO api_tokens (project_id, token_hash, label) VALUES ($1, $2, $3) RETURNING id, project_id, token_hash, label, last_used_at, created_at
`

type CreateTokenParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	TokenHash string    `json:"token_hash"`
	Label     string    `json:"label"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, createToken, arg.ProjectID, arg.TokenHash, arg.Label)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TokenHash,
		&i.Label,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteToken = `-- name: DeleteToken :exec
DELETE FROM api_tokens WHERE id = $1
`

func (q *Queries) DeleteToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteToken, id)
	return err
}

const getTokenByHash = `-- name: GetTokenByHash :one
SELECT id, project_id, token_hash, label, last_used_at, created_at FROM api_tokens WHERE token_hash = $1
`

func (q *Queries) GetTokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getTokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TokenHash,
		&i.Label,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listTokensByProject = `-- name: ListTokensByProject :many
SELECT id, project_id, token_hash, label, last_used_at, created_at FROM api_tokens WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTokensByProject(ctx context.Context, projectID uuid.UUID) ([]ApiToken, error) {
	rows, err := q.db.QueryContext(ctx, listTokensByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiToken
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TokenHash,
			&i.Label,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTokenLastUsed = `-- name: UpdateTokenLastUsed :exec
UPDATE api_tokens SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateTokenLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateTokenLastUsed, id)
	return err
}
